### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Saxavlax001** [RevivalTeam/Turanic#3]
- [ ] Add blocks,items,entities etc.

- [x] 1.3 update (when it comes)

- [x] Be a fork/spoon of altay/pmmp

- [ ] php 7.0 completely support(I can't do that)

- [x] add skin 128x128 support from altay
